---
# hosts, vms, and containers. To audit the inventory structure, run:
# ansible-inventory -i hosts.yml --graph

# 1. GROUP COMPOSITION (Groups of groups)
# These meta-groups combine the host groups above.
# The 'all' group implicitly contains everything.
# Global variables moved out of the implicit "all" group.

globals:
  vars: {}

# linux:
#   children:
#     containers:
#     workstation:
#     server:
#     proxmoxhosts:

# ----------------------------------------------------
# 2. HOST DEFINITIONS (Groups of hosts)
# These groups contain your actual servers.

containers:
  hosts:
    vdi.bruteware.cc: {}
    startbox.bruteware.cc: {}
    gitbox.bruteware.cc: {}

workstation:
  hosts:
    minty.bruteware.cc: {}
    buntu:
      gnome: true
    IdeaPad-Flex-5-14ALC05:
      gnome: true
      ansible_become_method: su
    macbookm2:
      mac: true

server:
  hosts:
    mediabox.bruteware.cc: {}
    gitrunner.bruteware.cc: {}
    stratolab.bruteware.cc: {}
    traefik-dashboard.bruteware.cc: {}

proxmoxhosts:
  hosts:
    192.168.10.11: {}
    192.168.10.12: {}
    192.168.10.13: {}
