---
- name: apt_update
  ansible.builtin.apt:
    update_cache: true

- name: restart_sshd
  ansible.builtin.service:
    name: "{{ openssh_service }}"
    state: restarted

- name: update_tmux_plugin_perms
  ansible.builtin.file:
    path: "{{ target_user_home }}/.tmux/plugins"
    owner: "{{ target_username }}"
    group: "{{ target_group }}"
    recurse: true

- name: update_vim_bundle_perms
  ansible.builtin.file:
    path: "{{ target_user_home }}/.vim/bundle"
    owner: "{{ target_username }}"
    group: "{{ target_group }}"
    recurse: true
