---
- name: apt_update
  apt: update_cache=yes

- name: restart_sshd
  service:
    name: "{{ openssh_service }}"
    state: restarted

- name: update_tmux_plugin_perms
  file:
    path: "{{ target_user_home }}/.tmux/plugins"
    owner: "{{ target_username }}"
    group: "{{ target_group }}"
    recurse: true

- name: update_vim_bundle_perms
  file:
    path: "{{ target_user_home }}/.vim/bundle"
    owner: "{{ target_username }}"
    group: "{{ target_group }}"
    recurse: true
