---
# Load distro-specific variables
- include_vars: "{{ ansible_facts['distribution'] }}.yml"
  tags: always

- block:
  ## User configs
  - import_tasks: users/brootware.yml


## desktop environments
  # - include_tasks: desktop_environments/mate/appearance.yml
  #   when: mate is defined and mate == true

  - include_tasks: desktop_environments/gnome/nautilus.yml

  ## system setup
  - import_tasks: system_setup/scripts.yml  

  ## install software
  - import_tasks: software/brave_browser.yml
  
  - import_tasks: software/snap_packages.yml
    when: ansible_facts['distribution'] == 'Ubuntu'