---
# Load distro-specific variables
- include_vars: "{{ ansible_facts['distribution'] }}.yml"
  tags: always

- block:
  ## User configs
  - import_tasks: users/brootware.yml


## desktop environments
  # sample task for mate if needed
  # - include_tasks: desktop_environments/mate/appearance.yml
  #   when: mate is defined and mate == true

  ## system setup
  - import_tasks: system_setup/scripts.yml  