---
# Load distro-specific variables
- ansible.builtin.include_vars: "{{ ansible_facts.distribution }}.yml"
  tags: always

- block:
    ## User configs
    - ansible.builtin.import_tasks: users/brootware.yml

    ## desktop environments
    - ansible.builtin.include_tasks: desktop_environments/gnome/nautilus.yml
      when: gnome is defined and gnome == true

    ## system setup
    - ansible.builtin.import_tasks: system_setup/scripts.yml

    ## install software
    - ansible.builtin.import_tasks: software/brave_browser.yml
    - ansible.builtin.import_tasks: software/steam.yml
    - ansible.builtin.import_tasks: software/snap_packages.yml
      when: ansible_facts.distribution == 'Ubuntu'
    - ansible.builtin.import_tasks: software/enable_rdp.yml
      when: ansible_facts.distribution == 'Linux Mint'
    - ansible.builtin.import_tasks: software/flatpak_packages.yml
      when: ansible_facts.distribution == 'Linux Mint'
    - ansible.builtin.import_tasks: software/gnome_packages.yml
      when: ansible_facts.distribution == 'Debian' or ansible_facts.distribution == 'Ubuntu'
    - ansible.builtin.import_tasks: software/sunshine.yml
      when: ansible_facts.distribution != 'Linux Mint'
