- name: mate | appearance | set wallpaper
  tags: mate,mate-wallpaper
  become_user: brootware
  dconf: key="/org/mate/desktop/background/{{ item.key }}" value={{ item.value}}
  with_items:
    - { key: "color-shading-type", value: "'vertical-gradient'" }
    - { key: "picture-filename", value: "'/usr/share/backgrounds/cosmos/background-1.xml'" }
    - { key: "picture-options", value: "'zoom'" }
    - { key: "primary-color", value: "'rgb(88,145,188)'" }
    - { key: "secondary-color", value: "'rgb(60,143,37)'" }