- name: users | brootware | create group
  tags: groups,brootware,users
  ansible.builtin.group:
    name: "{{ item.group }}"
    state: present
  loop:
    - { group: "{{ target_group }}" }
    - { group: ansible }

- name: users | brootware | create user
  tags: brootware,sudo,users
  ansible.builtin.user:
    name: "{{ target_username }}"
    group: "{{ target_group }}"
    groups: adm,ansible,{{ sudo_group }}
    state: present
    comment: "brootware "
    password: "{{ user_passwd | password_hash('sha512') }}"
    shell: /bin/bash

- name: users | brootware | brootware | add sudoers file
  tags: brootware,settings,goodegg,sudo,system,users
  ansible.builtin.copy:
    src: users/sudoers_brootware
    dest: /etc/sudoers.d/brootware
    owner: root
    group: root
    mode: "0440"

- name: users | brootware | create .ssh directory
  tags: dotfiles,brootware,ssh,users
  ansible.builtin.file:
    path: "{{ item.dir }}"
    state: directory
    owner: "{{ target_username }}"
    group: "{{ target_group }}"
    mode: "0700"
  loop:
    - { dir: '{{ target_user_home }}/.ssh' }
  become: true
  become_user: "{{ target_username }}"

- name: users | brootware | add public key
  tags: dotfiles,brootware,ssh,ssh-keys,users
  ansible.posix.authorized_key:
    user: brootware
    key: "{{ item }}"
  loop:
    - "{{ lookup('file', 'users/brootware/ssh/brootware_id_ed25519.pub') }}"
    - "{{ lookup('file', 'users/brootware/ssh/brootware_id_rsa.pub') }}"
