- name: users | brootware | create group
  tags: groups,brootware,users
  group:
    name: "{{ item.group }}"
    state: present
  with_items:
    - { group: brootware }
    - { group: ansible }

- name: users | brootware | create user
  tags: brootware,sudo,users
  user:
    name: brootware
    group: brootware
    groups: adm,ansible,{{ sudo_group }}
    state: present
    comment: "brootware "
    password: "{{ user_passwd | password_hash('sha512') }}"
    shell: /bin/bash

- name: users | brootware | brootware | add sudoers file
  tags: brootware,settings,goodegg,sudo,system,users
  copy:
    src: users/sudoers_brootware
    dest: /etc/sudoers.d/brootware
    owner: root
    group: root
    mode: 0440

- name: users | brootware | create .ssh directory
  tags: dotfiles,brootware,ssh,users
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: "{{ target_username }}"
    group: "{{ target_group }}"
    mode: 0700
  with_items:
    - { dir: '{{ target_user_home }}/.ssh' }
  become: true
  become_user: "{{ target_username }}"

- name: users | brootware | add public key
  tags: dotfiles,brootware,ssh,ssh-keys,users
  authorized_key:
    user: brootware
    key: "{{ item }}"
  with_file:
    - users/brootware/ssh/brootware_id_ed25519.pub
    - users/brootware/ssh/brootware_id_rsa.pub

- name: users | brootware | add ssh config file
  tags: dotfiles,brootware,ssh,users
  copy:
    src: users/brootware/ssh/config
    dest: "{{ target_user_home }}/.ssh/config"
    owner: "{{ target_username }}"
    group: "{{ target_group }}"
    mode: 0600