- name: users | goodegg | create user
  tags: goodegg,sudo,users
  user:
    name: goodegg
    group: brootware
    groups: adm,ansible,{{ sudo_group }}
    state: present
    comment: "goodegg "
    password: "{{ user_passwd | password_hash('sha512') }}"
    shell: /bin/bash

- name: users | goodegg | add public key
  tags: dotfiles,goodegg,ssh,ssh-keys,users
  authorized_key:
    user: goodegg
    key: "{{ item }}"
  with_file:
    - users/goodegg/ssh/goodegg_id_ed25519.pub

- name: users | goodegg | add sudoers file
  tags: settings,goodegg,sudo,system,users
  copy:
    src: users/sudoers_goodegg
    dest: /etc/sudoers.d/goodegg
    owner: root
    group: root
    mode: 0440
