- name: Download Brave browser GPG keyring
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    mode: '0644'

- name: Add Brave browser APT sources
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser.sources
    dest: /etc/apt/sources.list.d/brave-browser-release.sources
    mode: '0644'

- name: Install personalised ubuntu apt packages.
  ansible.builtin.apt:
    state: present
    name: brave-browser
    update_cache: true
    cache_valid_time: 86400
