- name: Install xrdp server
  ansible.builtin.apt:
    name: xrdp
    state: present
  become: true
  notify: Restart xrdp service

- name: Ensure .Xclients file exists for Cinnamon session
  ansible.builtin.lineinfile:
    path: "{{ target_user_home }}/.Xclients"
    line: cinnamon
    create: true
    owner: "{{ target_username }}"
    group: "{{ target_group }}"
    mode: '0755'
  become: true
  notify: Restart xrdp service

- name: Allow RDP port 3389 in ufw
  community.general.ufw:
    rule: allow
    port: '3389'
    proto: tcp
  become: true
