- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  ignore_errors: true
  package:
    state: latest
    name:
      - gnome-shell-extensions
      - gnome-tweaks
