# https://github.com/LizardByte/Sunshine/releases/latest/download/sunshine-ubuntu-26.04-amd64.deb

- name: Download Sunshine .deb package
  ansible.builtin.get_url:
    url: "https://github.com/LizardByte/Sunshine/releases/latest/download/{{ sunshine_package_name }}"
    dest: "{{ sunshine_download_path }}"
    mode: '0644'

- name: Install Sunshine and its dependencies
  ansible.builtin.apt:
    deb: "{{ sunshine_download_path }}"
    state: present

- name: Remove temporary deb file
  ansible.builtin.file:
    path: "{{ sunshine_download_path }}"
    state: absent

- name: Create user systemd directory
  ansible.builtin.file:
    path: "{{ target_user_home }}/.config/systemd/user"
    state: directory
    owner: "{{ target_username }}"
    group: "{{ target_group }}"
    mode: '0755'

- name: Copy Sunshine systemd service file
  ansible.builtin.copy:
    src: sunshine.service
    dest: "{{ target_user_home }}/.config/systemd/user/sunshine.service"
    owner: "{{ target_username }}"
    group: "{{ target_group }}"
    mode: '0644'

- name: Enable and start Sunshine user service
  ansible.builtin.systemd:
    name: sunshine
    state: started
    enabled: true
    scope: user
  become: true
  become_user: "{{ target_username }}"
