# Load distro-specific variables
- include_vars: "{{ ansible_facts.distribution }}.yml"
  tags: always

- block:
  - import_tasks: nrpe.yml
  # - import_tasks: ufw.yml
  - import_tasks: qemu-agent.yml

  - include_tasks: unattended_upgrades.yml
    when:
      - ansible_facts.distribution in ["Debian", "Ubuntu"]
      - unattended_upgrades is defined
      - unattended_upgrades == true

  rescue:
    - set_fact: task_failed=true
