# Load distro-specific variables
- ansible.builtin.include_vars: "{{ ansible_facts.distribution }}.yml"
  tags: always

- block:
    # - ansible.builtin.import_tasks: ufw.yml
    - ansible.builtin.import_tasks: proxmox_packages.yml
    - ansible.builtin.import_tasks: server_packages.yml
    - ansible.builtin.include_tasks: unattended_upgrades.yml
      when:
        - ansible_facts.distribution in ["Debian", "Ubuntu"]
        - unattended_upgrades is defined
        - unattended_upgrades == true

  rescue:
    - ansible.builtin.set_fact:
        task_failed: true
