- name: Proxmox packages | install package
  tags: packages,qemu,qemu-agent,spice,spice-agent,proxmox
  ansible.builtin.package:
    state: latest
    name:
      - qemu-guest-agent
      - spice-vdagent
  when: proxmox_instance is defined and proxmox_instance == true
  notify:
    - restart_qemu_agent
    - restart_spice_vdagent

- name: Proxmox packages | enable and start daemons
  tags: packages,qemu,qemu-agent,spice,spice-agent,proxmox
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - qemu-guest-agent
    - spice-vdagent
  when: proxmox_instance is defined and proxmox_instance == true
