- name: Server management packages | install package
  tags: packages,Server management packages
  ansible.builtin.package:
    state: latest
    name:
      - cockpit
  when: ansible_facts.distribution in ["Debian", "Linux Mint", "Ubuntu"]
  notify:
    - restart_cockpit_service

- name: Server management packages | enable service daemon
  ansible.builtin.service:
    name: cockpit
    enabled: true
    state: started
  when: ansible_facts.distribution in ["Debian", "Linux Mint", "Ubuntu"]