- name: ansible setup | ensure ansible is the latest version
  tags: ansible,ansible-setup
  package:
    name: ansible
    state: latest

- name: ansible setup | install required packages
  tags: ansible,ansible-setup,packages,onlydotfiles
  package:
    name:
      - "{{ dconf_package }}"
      - "{{ python_psutil_package }}"

# Note: For Arch, the requirement is met by a dependency of systemd, only necessary on Debian-based
- name: ansible setup | install acl package
  tags: ansible,ansible-setup,packages,onlydotfiles,mac
  package:
    name: acl
  when: ansible_facts.distribution in ["Debian", "Linux Mint", "Ubuntu"]

- name: ansible setup | remove default ansible directory (/etc/ansible) from host
  tags: ansible,ansible-setup,onlydotfiles,mac
  file:
    path: /etc/ansible
    state: absent
