- name: system setup | Install zsh plugins
  tags: onlydotfiles,mac,zsh
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/{{ item.plugin }}.git"
    dest: "{{ target_user_home }}/.oh-my-zsh/custom/plugins/{{ item.plugin }}"
    clone: yes
  with_items: 
    - { plugin: 'zsh-autosuggestions' }
    - { plugin: 'zsh-completions' }
  become: true
  become_user: "{{ target_username }}"