- name: system setup | Install zsh plugins
  tags: dotfiles,mac,zsh
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/{{ item.plugin }}.git"
    dest: "{{ ansible_facts.user_dir }}/.oh-my-zsh/custom/plugins/{{ item.plugin }}"
    clone: yes
  with_items: 
    - { plugin: 'zsh-autosuggestions' }
    - { plugin: 'zsh-completions' }