- name: mac setup | create .ssh directory
  tags: dotfiles,mac,ssh
  file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0700"

- name: mac setup | create config directories
  tags: dotfiles,mac,tmux,users,vim,zsh
  file:
    path: "{{ ansible_user_dir }}/{{ item.dir }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0700
  with_items:
    - { dir: '.bash' }
    - { dir: '.config' }
    - { dir: '.config/htop' }
    - { dir: '.config/mc' }
    - { dir: '.tmux' }
    - { dir: '.tmux/config' }
    - { dir: '.tmux/plugins' }
    - { dir: '.vim' }
    - { dir: '.vim/autoload' }
    - { dir: '.vim/bundle' }
    - { dir: '.vim/colors' }
    - { dir: '.vim/ftplugin' }
    - { dir: '.zsh' }