- name: mac setup | create .ssh directory
  tags: dotfiles,mac,ssh
  file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0700"

- name: mac setup | create config directories
  tags: dotfiles,mac,tmux,users,vim,zsh
  file:
    path: "{{ ansible_user_dir }}/{{ item.dir }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0700
  with_items:
    - { dir: '.bash' }
    - { dir: '.config' }
    - { dir: '.config/htop' }
    - { dir: '.config/mc' }
    - { dir: '.tmux' }
    - { dir: '.tmux/config' }
    - { dir: '.tmux/plugins' }
    - { dir: '.vim' }
    - { dir: '.vim/autoload' }
    - { dir: '.vim/bundle' }
    - { dir: '.vim/colors' }
    - { dir: '.vim/ftplugin' }
    - { dir: '.zsh' }

- name: mac setup | copy tmux config (server version)
  tags: dotfiles,mac,tmux,users,vim,zsh
  copy:
    src: users/brootware/tmux/tmux.conf.server
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0600
  when: "'server' not in group_names"

- name: mac setup | copy dotfiles
  tags: dotfiles,mac,tmux,users,vim,zsh
  copy:
    src: users/brootware/{{ item.src }}
    dest: "{{ ansible_user_dir }}/{{ item.dest }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0600
  with_items:
    - { src: 'bash/bash_aliases', dest: '.bash/bash_aliases' }
    - { src: 'bash/bash_profile', dest: '.bash_profile' }
    - { src: 'bash/bash_prompt', dest: '.bash/bash_prompt' }
    - { src: 'bash/bash_functions', dest: '.bash/bash_functions' }
    - { src: 'bash/bashrc', dest: '.bashrc' }
    - { src: 'bash/profile', dest: '.profile' }
    - { src: 'git/gitconfig', dest: '.gitconfig' }
    - { src: 'htop/htoprc', dest: '.config/htop/htoprc' }
    - { src: 'inputrc', dest: '.inputrc' }
    - { src: 'mc/mc.ini', dest: '.config/mc/ini' }
    - { src: 'vim/vimrc', dest: '.vimrc' }
    - { src: 'zsh/zshrc', dest: '.zshrc' }

- name: mac setup | copy individual zsh config files
  tags: dotfiles,mac,users,zsh
  copy:
    src: users/brootware/zsh/{{ item.src }}
    dest: "{{ ansible_user_dir }}/.zsh/{{ item.src }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0600
  with_items:
    - { src: 'aliases.zsh' }
    - { src: 'bindkey.zsh' }
    - { src: 'completion.zsh' }
    - { src: 'exports.zsh' }
    - { src: 'functions.zsh' }
    - { src: 'history.zsh' }
    - { src: 'path.zsh' }
    - { src: 'plugins.zsh' }
    - { src: 'prompt.zsh' }
    - { src: 'setopt.zsh' }
    - { src: 'theming.zsh' }

- name: mac setup | copy vim ftype files
  tags: dotfiles,mac,users,vim
  copy:
    src: users/brootware/vim/{{ item.src }}
    dest: "{{ ansible_user_dir }}/.vim/ftplugin/{{ item.src }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0600
  with_items:
    - { src: 'cmake.vim' }
    - { src: 'cpp.vim' }
    - { src: 'html.vim' }
    - { src: 'python.vim' }
    - { src: 'sql.vim' }
    - { src: 'xml.vim' }



