- name: only dotfiles setup | create .ssh directory
  tags: dotfiles,mac,ssh,users
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: "{{ target_username }}"
    group: "{{ target_group }}"
    mode: 0700
  with_items:
    - { dir: '{{ target_user_home }}/.ssh' }
  become: true
  become_user: "{{ target_username }}"

- name: only dotfiles setup | create config directories
  tags: dotfiles,mac,tmux,users,vim,zsh
  file:
    path: "{{ target_user_home }}/{{ item.dir }}"
    state: directory
    owner: "{{ target_username }}"
    group: "{{ target_group }}"
    mode: 0700
  with_items:
    - { dir: '.bash' }
    - { dir: '.config' }
    - { dir: '.config/htop' }
    - { dir: '.config/mc' }
    - { dir: '.tmux' }
    - { dir: '.tmux/config' }
    - { dir: '.tmux/plugins' }
    - { dir: '.vim' }
    - { dir: '.vim/autoload' }
    - { dir: '.vim/bundle' }
    - { dir: '.vim/colors' }
    - { dir: '.vim/ftplugin' }
    - { dir: '.zsh' }
  become: true
  become_user: "{{ target_username }}"

- name: only dotfiles setup | copy tmux config (server version)
  tags: dotfiles,mac,tmux,users,vim,zsh
  copy:
    src: users/brootware/tmux/tmux.conf.server
    dest: "{{ target_user_home }}/.tmux.conf"
    owner: "{{ target_username }}"
    group: "{{ target_group }}"
    mode: 0600
  when: "'server' not in group_names"
  become: true
  become_user: "{{ target_username }}"

- name: only dotfiles setup | clone tmux-completion plugin repository
  tags: dotfiles,mac,users,tmux
  git:
    repo: https://github.com/srsudar/tmux-completion.git
    dest: "{{ target_user_home }}/.tmux/plugins/completion"
    force: yes
  notify: update_tmux_plugin_perms
  become: true
  become_user: "{{ target_username }}"

- name: only dotfiles setup | clone tmux-continuum plugin repository
  tags: dotfiles,mac,users,tmux
  git:
    repo: https://github.com/tmux-plugins/tmux-continuum
    dest: "{{ target_user_home }}/.tmux/plugins/continuum"
    force: yes
  notify: update_tmux_plugin_perms
  become: true
  become_user: "{{ target_username }}"

- name: only dotfiles setup | clone tmux-resurrect plugin repository
  tags: dotfiles,mac,users,tmux
  git:
    repo: https://github.com/tmux-plugins/tmux-resurrect
    dest: "{{ target_user_home }}/.tmux/plugins/resurrect"
    force: yes
  notify: update_tmux_plugin_perms
  become: true
  become_user: "{{ target_username }}"

- name: only dotfiles setup | copy dotfiles
  tags: dotfiles,mac,tmux,users,vim,zsh
  copy:
    src: users/brootware/{{ item.src }}
    dest: "{{ target_user_home }}/{{ item.dest }}"
    owner: "{{ target_username }}"
    group: "{{ target_group }}"
    mode: 0600
  with_items:
    - { src: 'bash/bash_aliases', dest: '.bash/bash_aliases' }
    - { src: 'bash/bash_profile', dest: '.bash_profile' }
    - { src: 'bash/bash_prompt', dest: '.bash/bash_prompt' }
    - { src: 'bash/bash_functions', dest: '.bash/bash_functions' }
    - { src: 'bash/bashrc', dest: '.bashrc' }
    - { src: 'bash/profile', dest: '.profile' }
    - { src: 'git/gitconfig', dest: '.gitconfig' }
    - { src: 'htop/htoprc', dest: '.config/htop/htoprc' }
    - { src: 'inputrc', dest: '.inputrc' }
    - { src: 'mc/mc.ini', dest: '.config/mc/ini' }
    - { src: 'vim/vimrc', dest: '.vimrc' }
    - { src: 'zsh/zshrc', dest: '.zshrc' }
  become: true
  become_user: "{{ target_username }}"

- name: only dotfiles setup | copy individual zsh config files
  tags: dotfiles,mac,users,zsh
  copy:
    src: users/brootware/zsh/{{ item.src }}
    dest: "{{ target_user_home }}/.zsh/{{ item.src }}"
    owner: "{{ target_username }}"
    group: "{{ target_group }}"
    mode: 0600
  with_items:
    - { src: 'aliases.zsh' }
    - { src: 'bindkey.zsh' }
    - { src: 'completion.zsh' }
    - { src: 'exports.zsh' }
    - { src: 'functions.zsh' }
    - { src: 'history.zsh' }
    - { src: 'path.zsh' }
    - { src: 'plugins.zsh' }
    - { src: 'prompt.zsh' }
    - { src: 'setopt.zsh' }
    - { src: 'theming.zsh' }
  become: true
  become_user: "{{ target_username }}"

- name: only dotfiles setup | copy vim ftype files
  tags: dotfiles,mac,users,vim
  copy:
    src: users/brootware/vim/{{ item.src }}
    dest: "{{ target_user_home }}/.vim/ftplugin/{{ item.src }}"
    owner: "{{ target_username }}"
    group: "{{ target_group }}"
    mode: 0600
  with_items:
    - { src: 'cmake.vim' }
    - { src: 'cpp.vim' }
    - { src: 'html.vim' }
    - { src: 'python.vim' }
    - { src: 'sql.vim' }
    - { src: 'xml.vim' }
  become: true
  become_user: "{{ target_username }}"

- name: only dotfiles setup | copy vim color files
  tags: dotfiles,mac,users,vim
  copy:
    src: users/brootware/vim/{{ item.src }}
    dest: "{{ target_user_home }}/.vim/colors/{{ item.src }}"
    owner: "{{ target_username }}"
    group: "{{ target_group }}"
    mode: 0600
  with_items:
    - { src: 'bubblegum-256-dark.vim' }
    - { src: 'darktango.vim' }
    - { src: 'jellybeans.vim' }
    - { src: 'xoria256.vim' }
    - { src: 'zenburn.vim' }
  become: true
  become_user: "{{ target_username }}"

- name: only dotfiles setup | install pathogen
  tags: dotfiles,mac,users,vim
  copy:
    src: users/brootware/vim/{{ item.src }}
    dest: "{{ item.dest }}"
    owner: "{{ target_username }}"
    group: "{{ target_group }}"
    mode: 0700
  with_items:
    - { src: 'pathogen.vim', dest: '{{ target_user_home }}/.vim/autoload/pathogen.vim' }
  become: true
  become_user: "{{ target_username }}"


- name: only dotfiles setup | checkout git repositories for vim plugins
  tags: git,mac,users,vim
  become: true
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    force: yes
  with_items:
    - { repo: 'https://github.com/ctrlpvim/ctrlp.vim.git', dest: '{{ target_user_home }}/.vim/bundle/ctrlp.vim' }
    - { repo: 'https://github.com/davidhalter/jedi-vim.git', dest: '{{ target_user_home }}/.vim/bundle/jedi-vim' }
    - { repo: 'https://github.com/pearofducks/ansible-vim', dest: '{{ target_user_home }}/.vim/bundle/ansible-vim' }
    - { repo: 'https://github.com/rhysd/vim-grammarous.git', dest: '{{ target_user_home }}/.vim/bundle/vim-grammarous' }
    - { repo: 'https://github.com/ron89/thesaurus_query.vim', dest: '{{ target_user_home }}/.vim/bundle/thesaurus_query' }
    - { repo: 'https://github.com/scrooloose/nerdtree.git', dest: '{{ target_user_home }}/.vim/bundle/nerdtree' }
    - { repo: 'https://github.com/tpope/vim-obsession.git', dest: '{{ target_user_home }}/.vim/bundle/vim-obsession' }
    - { repo: 'https://github.com/vim-syntastic/syntastic.git', dest: '{{ target_user_home }}/.vim/bundle/syntastic' }
  notify: update_vim_bundle_perms
  become_user: "{{ target_username }}"
